# Generated by Django 3.0.4 on 2020-05-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=200)),
                ('cat_summary', models.CharField(max_length=200)),
                ('cat_slug', models.CharField(max_length=200)),
                ('image', models.ImageField(default='img/img.jpg', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
