# Generated by Django 3.0.4 on 2020-05-30 17:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='cat_summary',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('image', models.ImageField(default='img/img.jpg', upload_to='')),
                ('main_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.MainCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'MainFeild',
            },
        ),
        migrations.CreateModel(
            name='DoctorFullProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=200)),
                ('Specialize', models.CharField(max_length=200)),
                ('Sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=200)),
                ('DateOfBirth', models.DateField()),
                ('Phone_Number', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('Google_Address', models.CharField(max_length=200)),
                ('main_content', models.TextField()),
                ('date_published', models.DateTimeField(default=datetime.datetime(2020, 5, 30, 17, 26, 35, 440821), verbose_name='date published')),
                ('doctor_slug', models.CharField(default=1, max_length=200)),
                ('CoverPhoto', models.ImageField(blank=True, default='default.jpeg', upload_to='')),
                ('ProfilePic', models.ImageField(blank=True, default='doc...jpg', upload_to='')),
                ('speciality', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Specialization', verbose_name='MainFeild')),
            ],
        ),
    ]
