# Generated by Django 3.0.4 on 2020-05-30 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200530_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorfullprofile',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 18, 28, 10, 392811), verbose_name='date published'),
        ),
    ]
